src = ["src"]
cache-dir = ".cache/ruff"
line-length = 80
preview = true

[format]
docstring-code-format = true

[lint]
select = ["ALL"]
ignore = ["CPY", "ANN401", "D105"]

[lint.pydocstyle]
convention = "numpy"

[lint.per-file-ignores]
"docs/src/conf.py" = ["INP001"]
