src = ["src"]
cache-dir = ".cache/ruff"
line-length = 80
preview = true

[lint]
select = ["ALL"]
ignore = ["CPY", "D105", "S101", "ANN401"]

[lint.pydocstyle]
convention = "numpy"

[lint.extend-per-file-ignores]
"docs/src/conf.py" = ["INP001"]
"src/fastcc/codecs.py" = ["PLR6301", "D102"]
