src = ["src"]
cache-dir = ".cache/ruff"
line-length = 80
preview = true

[lint]
select = ["ALL"]
ignore = ["CPY"]

[lint.pydocstyle]
convention = "numpy"

[lint.extend-per-file-ignores]
"docs/src/conf.py" = ["INP001"]
